# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThriftStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bizID', models.IntegerField()),
                ('bizName', models.CharField(max_length=50)),
                ('bizCat', models.CharField(blank=True, default='', max_length=50)),
                ('bizCatSub', models.CharField(blank=True, default='', max_length=50)),
                ('bizAddr', models.CharField(max_length=100)),
                ('bizCity', models.CharField(max_length=50)),
                ('bizState', models.CharField(max_length=50)),
                ('bizZip', models.CharField(max_length=20)),
                ('bizPhone', models.CharField(blank=True, default='', max_length=50)),
                ('bizEmail', models.CharField(blank=True, default='', max_length=100)),
                ('bizURL', models.CharField(blank=True, default='', max_length=100)),
                ('locLat', models.FloatField(db_index=True)),
                ('locLong', models.FloatField(db_index=True)),
            ],
        ),
    ]
